name: "Context Workflows"

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: |
          echo "Hello $MY_ACTION"
          echo "HELLO $MY_ACTOR"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check result
        run: |
          echo "Test step outcome: ${{ steps.tests.outcome }}" 

      - name: Log workflow name
        run: |
          echo "Running workflow: ${{ github.workflow }}"
        
      

      
