name: "Workflow Commands"

on: ['push']

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: |
          echo "::group::My Group Message"
          echo "Message 1"
          echo "Message 2"
          echo ""::endgroup::""
      - name: "Step 1"
        run: |
          echo "MY_VAL=Hello World" >> $GITHUB_ENV
      - name: "Step 2"
        run: |
          echo $MY_VAL